import { db } from "@/lib/db";
import { getAdminOrResponse } from "@/lib/admin";
import { badRequest, errorResponse, ok } from "@/lib/http";
import { z } from "zod";

const imageSchema = z.object({ imageUrl: z.string().url(), altText: z.string().optional(), isPrimary: z.boolean().optional(), sortOrder: z.number().int().nonnegative().optional() });
const variantSchema = z.object({ sku: z.string().optional(), size: z.string().optional(), color: z.string().optional(), price: z.number().nonnegative().optional(), stockQuantity: z.number().int().nonnegative().default(0), isActive: z.boolean().optional() });
const productSchema = z.object({ name: z.string().min(2), slug: z.string().regex(/^[a-z0-9-]+$/), description: z.string().min(1), categoryId: z.string(), price: z.number().nonnegative(), basePrice: z.number().nonnegative().optional(), salePrice: z.number().nonnegative().nullable().optional(), compareAt: z.number().nonnegative().nullable().optional(), brand: z.string().optional(), sku: z.string().optional(), gender: z.enum(["MEN", "WOMEN", "KIDS", "UNISEX"]).optional(), imageUrl: z.string().url().nullable().optional(), stock: z.number().int().nonnegative().optional(), isFeatured: z.boolean().optional(), isNewArrival: z.boolean().optional(), isTrending: z.boolean().optional(), isActive: z.boolean().optional(), images: z.array(imageSchema).max(4).optional(), variants: z.array(variantSchema).optional() });

export async function GET() { const admin = await getAdminOrResponse(); if (admin instanceof Response) return admin; try { return ok({ products: await db.product.findMany({ include: { category: true, productImages: { orderBy: { sortOrder: "asc" } }, variants: { include: { inventory: true } } }, orderBy: { updatedAt: "desc" } }) }); } catch (error) { return errorResponse(error); } }

export async function POST(request: Request) { const admin = await getAdminOrResponse(); if (admin instanceof Response) return admin; try { const input = productSchema.parse(await request.json()); const category = await db.category.findFirst({ where: { id: input.categoryId, isActive: true } }); if (!category) return badRequest("Selected category does not exist or is inactive", 400); const { images, variants, ...data } = input; const product = await db.product.create({ data: { ...data, basePrice: data.basePrice ?? data.price, images: images ?? undefined, productImages: images ? { create: images } : undefined, variants: variants ? { create: variants.map((variant) => ({ ...variant, inventory: { create: { quantity: variant.stockQuantity, availableQuantity: variant.stockQuantity } } })) } : undefined }, include: { productImages: true, variants: { include: { inventory: true } } } }); return ok({ product }, 201); } catch (error) { return errorResponse(error); } }